<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny</AssemblyName>
    <PackageId>Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny</PackageId>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Sdcb.SimdPaddleOCR.ModelProvider\Sdcb.SimdPaddleOCR.ModelProvider.csproj" />
    <ProjectReference Include="..\Sdcb.SimdPaddleOCR.Models.TextLineOrientation\Sdcb.SimdPaddleOCR.Models.TextLineOrientation.csproj" />
    <EmbeddedResource Include="..\..\..\models\det.onnx" Link="det.onnx" />
    <EmbeddedResource Include="..\..\..\models\rec.onnx" Link="rec.onnx" />
    <EmbeddedResource Include="..\..\..\models\ppocr_keys.txt" Link="dict.txt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
